'use strict';
let builderMode='move',builderHistory=[];
function drawGrid(c,w,h,step){c.save();c.strokeStyle='#e8e8e8';c.lineWidth=.7;for(let x=0;x<=w;x+=step){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke()}for(let y=0;y<=h;y+=step){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke()}c.restore()}
function blankFigure(){return normalize({id:++serial,name:'Untitled figure',color:'#000000',parents:[-1],points:[[400,350]],scale:100})}
function beginBuilder(f,id){stop();draft=normalize(clone(f));draftId=id;draftOriginal=JSON.stringify(draft);builderHistory=[];segment=0;builderMode='move';$('figureName').value=draft.name;$('builder').hidden=false;$('builder').classList.remove('minimized');paintBuilder()}
function openBuilder(){if(chosen())beginBuilder(chosen(),selected)}
function createFigure(){closeBuilder(true);if(frame().figures.length>=50)return say('50-figure limit reached.');beginBuilder(blankFigure(),null)}
function draftSnapshot(){builderHistory.push(JSON.stringify({draft,segment}));if(builderHistory.length>60)builderHistory.shift()}
function undoBuilder(){if(!builderHistory.length)return;const previous=JSON.parse(builderHistory.pop());draft=previous.draft;segment=previous.segment;$('figureName').value=draft.name;paintBuilder()}
function closeBuilder(apply){if(!draft)return;if(apply){draft.name=$('figureName').value.trim()||'Untitled figure';if(draftId===null){if(frame().figures.length>=50){say('50-figure limit reached. Save this figure to the library.');return}snapshot();const f=clone(draft);f.templatePoints=clone(f.points);frame().figures.push(f);selected=f.id;update();say('Added “'+f.name+'”.')}else{const f=frame().figures.find(f=>f.id===draftId);if(f&&draftOriginal!==JSON.stringify(draft)){snapshot();draft.templatePoints=clone(draft.points);Object.assign(f,clone(draft));update();say('Figure changes applied.')}}}draft=null;builderDrag=null;$('builder').hidden=true}
function paintBuilder(){if(!draft||$('builder').hidden||$('builder').classList.contains('minimized'))return;const {c,w,h}=sizeCanvas($('builderCanvas'));c.fillStyle='#fff';c.fillRect(0,0,w,h);const origin=draft.points[0];
  if(!builderDrag){const xs=draft.points.map(p=>p[0]-origin[0]),ys=draft.points.map(p=>p[1]-origin[1]);const extentX=Math.max(145,...xs.map(Math.abs))+20,extentY=Math.max(160,...ys.map(Math.abs))+20;const scale=Math.min(w/(extentX*2),h/(extentY*2));builderView={scale,x:w/2-origin[0]*scale,y:h/2-origin[1]*scale}}
  c.save();c.translate(builderView.x,builderView.y);c.scale(builderView.scale,builderView.scale);
  if($('builderSnap').checked){c.save();c.strokeStyle='#ededed';c.lineWidth=.5/builderView.scale;const v=builderView,step=10;for(let x=Math.ceil(-v.x/v.scale/step)*step;x<(w-v.x)/v.scale;x+=step){c.beginPath();c.moveTo(x,-v.y/v.scale);c.lineTo(x,(h-v.y)/v.scale);c.stroke()}for(let y=Math.ceil(-v.y/v.scale/step)*step;y<(h-v.y)/v.scale;y+=step){c.beginPath();c.moveTo(-v.x/v.scale,y);c.lineTo((w-v.x)/v.scale,y);c.stroke()}c.restore()}
  drawFigure(c,draft,false,true,segment);const joint=draft.points[segment];c.beginPath();c.arc(...joint,11,0,Math.PI*2);c.strokeStyle='#0000ff';c.lineWidth=2;c.stroke();c.restore();
  const a=draft.points[draft.parents[segment]],b=draft.points[segment];$('builderStatus').textContent=segment===0?'Origin · '+draft.points.length+' joints':`Joint ${segment} · ${draft.types[segment]} · width ${Math.round(draft.widths[segment])} · length ${Math.round(Math.hypot(a[0]-b[0],a[1]-b[1]))}`;
  $('builderCaption').textContent=draft.name+' — Figure Builder';$('builderHint').textContent=builderMode==='move'?'Drag a joint to reshape. Select a joint, then + Line or + Circle to draw.':'Click a joint to start a branch; click empty space to add a '+builderMode+'. Esc cancels drawing.';
  for(const [id,mode]of [['selectTool','move'],['addLineTool','line'],['addCircleTool','circle']])$(id).setAttribute('aria-pressed',String(builderMode===mode));
  for(const id of ['lineTool','circleTool','fillTool','thicker','thinner','dynamicTool','removeSegment','deleteBranch'])$(id).disabled=segment===0;
  $('dynamicTool').setAttribute('aria-pressed',String(draft.fixed[segment]));$('undoBuilder').disabled=!builderHistory.length;
}
function builderPoint(e){const r=$('builderCanvas').getBoundingClientRect(),v=builderView;return[(e.clientX-r.left-v.x)/v.scale,(e.clientY-r.top-v.y)/v.scale]}
function snapBuilder(p,exclude=-1){if(!$('builderSnap').checked)return p;let nearest=null,distance=8/builderView.scale;draft.points.forEach((q,i)=>{if(i===exclude||draft.hidden[i])return;const d=Math.hypot(q[0]-p[0],q[1]-p[1]);if(d<distance){nearest=q;distance=d}});return nearest?nearest.slice():p.map(v=>Math.round(v/10)*10)}
function hitBuilder(p){let index=-1,distance=10/builderView.scale;draft.points.forEach((q,i)=>{if(draft.hidden[i])return;const d=Math.hypot(q[0]-p[0],q[1]-p[1]);if(d<distance){index=i;distance=d}});return index}
$('builderCanvas').onpointerdown=e=>{if(!draft||e.button!==0)return;const p=builderPoint(e),hit=hitBuilder(p);if(builderMode!=='move'){
  if(hit>=0){segment=hit;paintBuilder();return}if(draft.points.length>=128){$('builderHint').textContent='128-joint limit reached.';return}const next=snapBuilder(p),origin=draft.points[segment];if(Math.hypot(next[0]-origin[0],next[1]-origin[1])<2)return;draftSnapshot();draft.parents.push(segment);draft.points.push(next);draft.widths.push(9);draft.types.push(builderMode);for(const key of ['fixed','hidden','filled','pinned'])draft[key].push(false);segment=draft.points.length-1;draft.templatePoints=clone(draft.points);paintBuilder();return;
}if(hit<0)return;segment=hit;draftSnapshot();builderDrag={i:hit,p,original:clone(draft.points),view:{...builderView}};$('builderCanvas').setPointerCapture(e.pointerId);paintBuilder()};
$('builderCanvas').onpointermove=e=>{if(!builderDrag||!draft)return;const p=snapBuilder(builderPoint(e),builderDrag.i),old=builderDrag.original[builderDrag.i],dx=p[0]-old[0],dy=p[1]-old[1];draft.points=builderDrag.original.map((q,i)=>builderDrag.i===0?[q[0]+dx,q[1]+dy]:i===builderDrag.i?p.slice():q.slice());paintBuilder()};
$('builderCanvas').onpointerup=$('builderCanvas').onpointercancel=()=>{if(builderDrag){builderDrag=null;draft.templatePoints=clone(draft.points);paintBuilder()}};
for(const [id,mode]of [['selectTool','move'],['addLineTool','line'],['addCircleTool','circle']])$(id).onclick=()=>{builderMode=mode;paintBuilder()};
$('builderSnap').onchange=paintBuilder;
$('figureName').onchange=()=>{if(!draft)return;draftSnapshot();draft.name=$('figureName').value.trim()||'Untitled figure';paintBuilder()};
function editSegment(fn){if(!draft||segment===0)return;draftSnapshot();fn();paintBuilder()}
$('lineTool').onclick=()=>editSegment(()=>draft.types[segment]='line');$('circleTool').onclick=()=>editSegment(()=>draft.types[segment]='circle');$('fillTool').onclick=()=>editSegment(()=>{draft.types[segment]='circle';draft.filled[segment]=!draft.filled[segment]});
for(const[id,n]of [['thicker',1],['thinner',-1]])$(id).onclick=()=>editSegment(()=>draft.widths[segment]=Math.max(1,Math.min(40,draft.widths[segment]+n)));
$('dynamicTool').onclick=()=>editSegment(()=>draft.fixed[segment]=!draft.fixed[segment]);
$('removeSegment').onclick=()=>editSegment(()=>draft.hidden=draft.hidden.map((v,i)=>v||Rig.descendant(draft.parents,segment,i)));
$('restoreSegments').onclick=()=>{if(draft){draftSnapshot();draft.hidden.fill(false);paintBuilder()}};
$('deleteBranch').onclick=()=>editSegment(()=>{const keep=draft.points.map((_,i)=>i).filter(i=>!Rig.descendant(draft.parents,segment,i));const map=new Map(keep.map((id,i)=>[id,i]));draft.parents=keep.map(i=>i===0?-1:map.get(draft.parents[i]));for(const key of ['points','widths','types','fixed','hidden','filled','pinned'])draft[key]=keep.map(i=>draft[key][i]);draft.templatePoints=clone(draft.points);segment=0});
$('blankBuilder').onclick=()=>{if(!draft)return;draftSnapshot();const f=blankFigure();f.id=draft.id;draft=f;segment=0;builderMode='line';$('figureName').value=draft.name;paintBuilder()};
$('resetBuilder').onclick=()=>{if(!draft)return;draftSnapshot();const f=normalize(figure(...draft.points[0]));f.id=draft.id;f.name=draft.name;draft=f;segment=1;paintBuilder()};
function saveDraftLibrary(){if(!draft)return;draft.name=$('figureName').value.trim()||'Untitled figure';const f=cleanFigure(draft);f.templatePoints=clone(f.points);f.id=1;const name=uniqueName(draft.name,'characters'),record={id:freshAssetId(),name,figure:f};if(!validAsset(record,'characters')){$('builderHint').textContent='Invalid figure. Check its joints before saving.';return}const next=clone(assetLibrary);next.characters.push(record);if(persistLibrary(next)){$('builderHint').textContent='Saved “'+name+'”. Choose it in Figure type → Add Figure.';say('Saved figure “'+name+'” to the library.')}else $('builderHint').textContent=$('libraryStatus').textContent}
$('saveNamedFigure').onclick=$('saveBuilderRig').onclick=saveDraftLibrary;
$('exportBuilder').onclick=()=>{if(!draft)return;draft.name=$('figureName').value.trim()||'Untitled figure';const f=cleanFigure(draft);f.templatePoints=clone(f.points);download(new Blob([JSON.stringify({format:'frame-by-frame-figure',version:1,figure:f},null,2)],{type:'application/json'}),(draft.name.replace(/[^a-z0-9-]+/gi,'-')||'figure')+'.json');$('builderHint').textContent='Figure exported. Open it again with File → Open figure.'};
$('newFigure').onclick=createFigure;$('openFigure').onclick=()=>$('figureFile').click();
$('figureFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1e6)throw Error();const data=JSON.parse(await file.text());if(data.format!=='frame-by-frame-figure'||data.version!==1||!Rig.validFigure(data.figure))throw Error();if(frame().figures.length>=50)throw Error();closeBuilder(true);const f=cleanFigure(data.figure);f.id=++serial;beginBuilder(f,null);say('Figure opened. Save to library or apply to the frame.')}catch{say('Could not open figure. Choose valid figure JSON under 1 MB and keep fewer than 50 figures in this frame.')}e.target.value=''};
$('edit').onclick=openBuilder;$('builderClose').onclick=$('applyBuilder').onclick=()=>closeBuilder(true);$('cancelBuilder').onclick=()=>closeBuilder(false);$('undoBuilder').onclick=undoBuilder;
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&draft&&builderMode!=='move'){e.preventDefault();e.stopImmediatePropagation();builderMode='move';paintBuilder()}},true);
const preferenceIds=['onion','pullJoints','showJoints','stageGrid','angleSnap','loop','builderSnap'];
try{const saved=JSON.parse(localStorage.getItem('frame-by-frame-preferences-v1'));for(const id of preferenceIds)if(typeof saved?.[id]==='boolean')$(id).checked=saved[id]}catch{}
function savePreferences(){try{localStorage.setItem('frame-by-frame-preferences-v1',JSON.stringify(Object.fromEntries(preferenceIds.map(id=>[id,$(id).checked]))))}catch{say('Preferences could not be saved in this browser.')}}
for(const id of preferenceIds)$(id).addEventListener('change',()=>{savePreferences();paint();paintBuilder()});
$('releasePins').onclick=()=>{if(chosen())mutate(()=>{normalize(chosen()).pinned.fill(false);say('All pins on the selected figure released.')})};
function openSettings(){$('settingsFps').value=$('fps').value;settingsDuration();$('settingsDialog').showModal()}
function settingsDuration(){const n=+$('settingsFps').value;$('settingsDuration').textContent=n>=1&&n<=30?frames.length+' frames · '+(frames.length/n).toFixed(2)+' seconds':'Choose 1–30 frames per second.'}
$('settingsFps').oninput=settingsDuration;
$('settingsForm').onsubmit=e=>{if(e.submitter?.value!=='apply')return;const fps=+$('settingsFps').value;if(!Number.isInteger(fps)||fps<1||fps>30){e.preventDefault();return}snapshot();$('fps').value=fps;speedLabel();persist();say('Animation speed set to '+fps+' fps.')};
