'use strict';
const $=id=>document.getElementById(id), W=800,H=660,cv=$('stage'),ctx=cv.getContext('2d');
const parents=[-1,0,1,1,3,1,5,0,7,0,9];
const base=[[0,0],[0,-94],[0,-150],[-38,-58],[-65,3],[38,-58],[65,3],[-30,74],[-51,146],[30,74],[51,146]];
const clone=v=>JSON.parse(JSON.stringify(v));
let serial=0,current=0,selected,frames=[],playing=false,playIndex=0,lastTime=0,history=[],drag=null;
let draft=null,draftId=null,draftOriginal='',segment=1,builderDrag=null,builderView={scale:1,x:0,y:0};
const builderBase=[[0,0],[0,-78],[0,-124],[-36,-41],[-62,3],[36,-41],[62,3],[-25,60],[-49,120],[25,60],[49,120]];
function figure(x=144,y=350){return{id:++serial,color:'#000000',points:base.map(p=>[x+p[0],y+p[1]]),templatePoints:builderBase.map(p=>[x+p[0],y+p[1]]),scale:100,widths:Array(11).fill(9),types:Array.from({length:11},(_,i)=>i===2?'circle':'line'),fixed:Array(11).fill(false),hidden:Array(11).fill(false),filled:Array(11).fill(false)}}
const frame=()=>frames[current],chosen=()=>frame()?.figures.find(f=>f.id===selected);
function say(text){$('notice').textContent=text;cv.title=text}
function normalize(f){f.widths??=Array(11).fill(9);f.types??=Array.from({length:11},(_,i)=>i===2?'circle':'line');f.fixed??=Array(11).fill(false);f.hidden??=Array(11).fill(false);f.filled??=Array(11).fill(false);f.scale??=100;return f}
function sample(){const f=figure();const poses=[[-22,31],[-35,20],[-47,10],[-25,16],[-5,5],[-7,9]];frames=poses.map(([a,b],i)=>{let g=clone(f);const offset=i===4?128:0;g.points.forEach(p=>p[0]+=offset);g.points[3]=[144+offset+a,318];g.points[4]=[144+offset+a-6,380];g.points[5]=[144+offset+b,318];g.points[6]=[144+offset+b+26,378];g.points[7]=[127+offset,426];g.points[8]=[104+offset,500];g.points[9]=[166+offset,426];g.points[10]=[172+offset,502];return{figures:[g]}});current=5;selected=f.id}
function validPoints(p){return Array.isArray(p)&&p.length===11&&p.every(q=>Array.isArray(q)&&q.length===2&&q.every(v=>Number.isFinite(v)&&Math.abs(v)<100000))}
function valid(data){return data&&data.version===1&&Number.isFinite(data.fps)&&data.fps>=1&&data.fps<=30&&Array.isArray(data.frames)&&data.frames.length>0&&data.frames.length<=500&&data.frames.every(fr=>fr&&Array.isArray(fr.figures)&&fr.figures.length<=50&&new Set(fr.figures.map(f=>f?.id)).size===fr.figures.length&&fr.figures.every(f=>f&&Number.isSafeInteger(f.id)&&f.id>=0&&f.id<1e9&&typeof f.color==='string'&&/^#[0-9a-f]{6}$/i.test(f.color)&&Array.isArray(f.points)&&f.points.length===11&&f.points.every(p=>Array.isArray(p)&&p.length===2&&p.every(v=>Number.isFinite(v)&&Math.abs(v)<100000))&&(f.templatePoints===undefined||validPoints(f.templatePoints))&&['widths','types','fixed','hidden','filled'].every(k=>f[k]===undefined||(Array.isArray(f[k])&&f[k].length===11&&f[k].every(v=>k==='widths'?Number.isFinite(v)&&v>=1&&v<=40:k==='types'?['line','circle'].includes(v):typeof v==='boolean')))&&(f.scale===undefined||(Number.isFinite(f.scale)&&f.scale>=10&&f.scale<=400))))}
function persist(){try{localStorage.setItem('frame-by-frame-v1',JSON.stringify({version:1,frames,fps:+$('fps').value}))}catch{say('Browser storage unavailable. Save your project from the File menu.')}}
function adopt(data){frames=clone(data.frames);frames.forEach(fr=>fr.figures.forEach(normalize));serial=Math.max(0,...frames.flatMap(fr=>fr.figures.map(f=>f.id)));current=0;selected=frame().figures[0]?.id;$('fps').value=data.fps;history=[];closeBuilder(false);playing=false;update();speedLabel()}
function snapshot(){history.push(JSON.stringify({frames,current,selected}));if(history.length>60)history.shift()}
function mutate(fn){stop();closeBuilder(true);snapshot();fn();update()}
function view(){const r=cv.getBoundingClientRect(),s=Math.min(r.width/W,r.height/H);return{scale:s,x:0,y:0,width:r.width,height:r.height}}
function sizeCanvas(canvas){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d)}const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);return{c,w:r.width,h:r.height}}
function drawFigure(c,f,ghost=false,handles=false,highlight=-1){const p=f.points;c.save();c.lineCap='round';c.lineJoin='round';for(let i=1;i<p.length;i++){if(f.hidden?.[i])continue;const a=p[parents[i]],b=p[i];c.strokeStyle=ghost?'#bfbfbf':i===highlight?'#0000ff':f.color;c.lineWidth=f.widths?.[i]||9;c.fillStyle=c.strokeStyle;c.beginPath();if((f.types?.[i]||(i===2?'circle':'line'))==='circle'){c.arc((a[0]+b[0])/2,(a[1]+b[1])/2,Math.hypot(a[0]-b[0],a[1]-b[1])/2,0,Math.PI*2);if(f.filled?.[i])c.fill();else c.stroke()}else{c.moveTo(...a);c.lineTo(...b);c.stroke()}}if(handles)p.forEach((pt,i)=>{if(f.hidden?.[i])return;c.beginPath();c.arc(...pt,7,0,Math.PI*2);c.fillStyle=i===0?'#ff9900':f.fixed?.[i]?'#808080':'#ff0000';c.fill()});c.restore()}
function paint(){if(!frame())return;const {c,w,h}=sizeCanvas(cv),v=view();c.fillStyle='#fff';c.fillRect(0,0,w,h);c.save();c.translate(v.x,v.y);c.scale(v.scale,v.scale);const idx=playing?playIndex:current;if(!playing&&$('onion').checked&&current>0)frames[current-1].figures.forEach(f=>drawFigure(c,f,true));frames[idx]?.figures.forEach(f=>drawFigure(c,f,false,!playing));c.restore();$('stageTitle').textContent=(playing?'Playing frame ':'Frame ')+(idx+1)}
function timeline(){const el=$('frames');el.replaceChildren();frames.forEach((fr,i)=>{const b=document.createElement('button');b.className='frame'+(i===current?' active':'');b.setAttribute('aria-label','Select frame '+(i+1));b.setAttribute('aria-pressed',String(i===current));b.title='Frame '+(i+1);const c=document.createElement('canvas');c.width=134;c.height=110;const x=c.getContext('2d');x.scale(134/W,110/H);fr.figures.forEach(f=>drawFigure(x,f));b.append(c);b.onclick=()=>{closeBuilder(true);stop();current=i;selected=frame().figures[0]?.id;update(false)};el.append(b)});$('duration').textContent=frames.length+' frames · '+(frames.length/+$('fps').value).toFixed(2)+' seconds';$('deleteFrame').disabled=frames.length===1}
function update(save=true){paint();timeline();const f=chosen();if(f){$('color').value=f.color;$('scale').value=f.scale||100}for(const id of ['deleteFigure','copyFigure','edit','flip','center','smaller','larger','colour','scale','front','back'])$(id).disabled=!f;if(save)persist()}
function stop(){playing=false;$('playText').textContent='Play';paint()}
function toggle(){if(playing){stop();return}closeBuilder(true);playing=true;playIndex=current;lastTime=performance.now();$('playText').textContent='Pause';paint()}
function tick(t){if(playing&&t-lastTime>=1000/+$('fps').value){lastTime=t;playIndex++;if(playIndex>=frames.length){if($('loop').checked)playIndex=0;else{stop();requestAnimationFrame(tick);return}}paint()}requestAnimationFrame(tick)}
function addFrame(){if(frames.length>=500)return say('500-frame limit reached.');mutate(()=>{frames.splice(current+1,0,clone(frame()));current++});$('frames').children[current].scrollIntoView({block:'nearest',inline:'nearest'});say('Frame '+(current+1)+' added.')}
function undo(){closeBuilder(false);if(!history.length)return say('No edits to undo.');stop();const s=JSON.parse(history.pop());frames=s.frames;current=s.current;selected=s.selected;update();say('Last edit undone.')}
function scaleFigure(factor){if(!chosen())return;mutate(()=>{const f=chosen(),o=f.points[0].slice(),next=Math.max(10,Math.min(400,(f.scale||100)*factor)),ratio=next/(f.scale||100);f.points=f.points.map(p=>[o[0]+(p[0]-o[0])*ratio,o[1]+(p[1]-o[1])*ratio]);if(f.templatePoints){const t=f.templatePoints[0];f.templatePoints=f.templatePoints.map(p=>[t[0]+(p[0]-t[0])*ratio,t[1]+(p[1]-t[1])*ratio])}f.widths=f.widths.map(w=>Math.max(1,Math.min(40,w*ratio)));f.scale=next})}
function subtree(i,j){let n=j;while(n>0&&n!==i)n=parents[n];return n===i}
function point(e){const r=cv.getBoundingClientRect(),v=view();return[(e.clientX-r.left-v.x)/v.scale,(e.clientY-r.top-v.y)/v.scale]}
cv.onpointerdown=e=>{if(e.button!==0)return;closeBuilder(true);stop();const p=point(e);let hit=null;for(const f of [...frame().figures].reverse())f.points.forEach((pt,i)=>{if(f.hidden?.[i]||f.fixed?.[i])return;const d=Math.hypot(p[0]-pt[0],p[1]-pt[1]);if(d<14&&(!hit||d<hit.d))hit={f,i,d}});if(!hit)return;snapshot();selected=hit.f.id;drag={f:hit.f,i:hit.i,start:p,original:clone(hit.f.points)};cv.setPointerCapture(e.pointerId);paint()};
cv.onpointermove=e=>{if(!drag)return;const p=point(e),{f,i,start,original}=drag;if(i===0){const dx=p[0]-start[0],dy=p[1]-start[1];f.points=original.map(q=>[q[0]+dx,q[1]+dy])}else{const o=original[parents[i]],angle=Math.atan2(p[1]-o[1],p[0]-o[0])-Math.atan2(original[i][1]-o[1],original[i][0]-o[0]),cos=Math.cos(angle),sin=Math.sin(angle);f.points=original.map((q,j)=>{if(!subtree(i,j))return q.slice();const dx=q[0]-o[0],dy=q[1]-o[1];return[o[0]+dx*cos-dy*sin,o[1]+dx*sin+dy*cos]})}paint()};
function endDrag(){if(drag){drag=null;update();say('Pose updated.')}}cv.onpointerup=endDrag;cv.onpointercancel=endDrag;
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function speedLabel(){$('fpsval').textContent=$('fps').value;$('fps').title='Animation speed: '+$('fps').value+' fps';timeline()}
$('next').onclick=addFrame;$('duplicate').onclick=addFrame;$('deleteFrame').onclick=()=>{if(frames.length>1)mutate(()=>{frames.splice(current,1);current=Math.min(current,frames.length-1);selected=frame().figures[0]?.id})};$('play').onclick=toggle;$('stop').onclick=stop;
$('fps').oninput=()=>{speedLabel();persist()};for(const [id,delta]of [['speedUp',1],['speedDown',-1]])$(id).onclick=()=>{$('fps').value=Math.max(1,Math.min(30,+$('fps').value+delta));speedLabel();persist()};$('speedInfo').onclick=()=>{say('Use the vertical slider beside Play and Stop to set the frame rate.');$('fps').focus()};$('onion').onchange=paint;
$('add').onclick=()=>{if(frame().figures.length>=50)return say('50-figure limit reached.');mutate(()=>{const f=figure(380,350);frame().figures.push(f);selected=f.id})};$('deleteFigure').onclick=()=>mutate(()=>{frame().figures=frame().figures.filter(f=>f.id!==selected);selected=frame().figures[0]?.id});$('copyFigure').onclick=()=>{if(chosen()&&frame().figures.length<50)mutate(()=>{const f=clone(chosen());f.id=++serial;f.points.forEach(p=>p[0]+=40);frame().figures.push(f);selected=f.id})};$('flip').onclick=()=>{if(chosen())mutate(()=>{const f=chosen(),x=f.points[0][0];f.points.forEach(p=>p[0]=2*x-p[0])})};$('center').onclick=()=>{if(chosen())mutate(()=>{const f=chosen(),dx=400-f.points[0][0],dy=350-f.points[0][1];f.points.forEach(p=>{p[0]+=dx;p[1]+=dy})})};$('smaller').onclick=()=>scaleFigure(.9);$('larger').onclick=()=>scaleFigure(1.1);$('scale').onchange=()=>{const n=+$('scale').value;if(Number.isFinite(n)&&n>0&&chosen())scaleFigure(n/(chosen().scale||100))};$('colour').onclick=()=>$('color').click();$('color').onchange=()=>{if(chosen())mutate(()=>chosen().color=$('color').value)};for(const [id,front]of [['front',true],['back',false]])$(id).onclick=()=>{if(chosen())mutate(()=>{const f=chosen();frame().figures=frame().figures.filter(x=>x.id!==selected);if(front)frame().figures.push(f);else frame().figures.unshift(f)})};$('undo').onclick=undo;
$('save').onclick=()=>{closeBuilder(true);download(new Blob([JSON.stringify({version:1,frames,fps:+$('fps').value},null,2)],{type:'application/json'}),'frame-by-frame.json');say('Project downloaded.')};$('load').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5e6)throw Error();const d=JSON.parse(await f.text());if(!valid(d))throw Error();adopt(d);say('Project opened: '+frames.length+' frames.')}catch{say('Could not open project. Choose valid Frame by Frame JSON (max 5 MB).')}$('file').value=''};
$('export').onclick=()=>{closeBuilder(true);const c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,W,H);frame().figures.forEach(f=>drawFigure(x,f));c.toBlob(b=>download(b,'frame-'+(current+1)+'.png'))};$('new').onclick=()=>{if(!confirm('Start a new animation? Save your current animation first.'))return;mutate(()=>{const f=figure(400,350);frames=[{figures:[f]}];current=0;selected=f.id})};$('demo').onclick=()=>{if(!confirm('Load the six-frame example? Undo restores your current project.'))return;mutate(sample);openBuilder()};
// The builder edits a copy; closing with X applies one undoable edit.
function openBuilder(){if(!chosen())return;stop();draft=normalize(clone(chosen()));if(draft.templatePoints){const o=draft.points[0],t=draft.templatePoints[0];draft.points=draft.templatePoints.map(p=>[p[0]+o[0]-t[0],p[1]+o[1]-t[1]])}draftOriginal=JSON.stringify(draft);draftId=selected;segment=1;$('builder').hidden=false;$('builder').classList.remove('minimized');paintBuilder()}
function closeBuilder(apply){if(!draft)return;if(apply){const f=frame().figures.find(f=>f.id===draftId);if(f&&draftOriginal!==JSON.stringify(draft)){snapshot();draft.templatePoints=clone(draft.points);Object.assign(f,clone(draft));update();say('Figure changes applied.')}}draft=null;builderDrag=null;$('builder').hidden=true}
function paintBuilder(){if(!draft||$('builder').hidden||$('builder').classList.contains('minimized'))return;const {c,w,h}=sizeCanvas($('builderCanvas'));c.fillStyle='#fff';c.fillRect(0,0,w,h);const origin=draft.points[0],s=Math.min(w/290,h/400);builderView={scale:s,x:w/2-origin[0]*s,y:h/2-origin[1]*s};c.save();c.translate(builderView.x,builderView.y);c.scale(s,s);drawFigure(c,draft,false,true,segment);c.restore();const a=draft.points[parents[segment]],b=draft.points[segment];$('builderStatus').textContent=draft.types[segment]+': thickness '+Math.round(draft.widths[segment]/1.3)+', length '+Math.round(Math.hypot(a[0]-b[0],a[1]-b[1])/1.3)+', '+(draft.fixed[segment]?'static':'dynamic');$('dynamicTool').setAttribute('aria-pressed',String(draft.fixed[segment]))}
function builderPoint(e){const r=$('builderCanvas').getBoundingClientRect();return[(e.clientX-r.left-builderView.x)/builderView.scale,(e.clientY-r.top-builderView.y)/builderView.scale]}
$('builderCanvas').onpointerdown=e=>{if(!draft||e.button!==0)return;const p=builderPoint(e);let nearest=-1,dist=18;draft.points.forEach((q,i)=>{if(draft.hidden[i])return;const d=Math.hypot(q[0]-p[0],q[1]-p[1]);if(d<dist){nearest=i;dist=d}});if(nearest<0)return;segment=nearest||1;builderDrag={i:nearest,p,original:clone(draft.points),view:{...builderView}};$('builderCanvas').setPointerCapture(e.pointerId);paintBuilder()};
$('builderCanvas').onpointermove=e=>{if(!builderDrag||!draft)return;const r=$('builderCanvas').getBoundingClientRect(),v=builderDrag.view,p=[(e.clientX-r.left-v.x)/v.scale,(e.clientY-r.top-v.y)/v.scale],dx=p[0]-builderDrag.p[0],dy=p[1]-builderDrag.p[1];draft.points=builderDrag.original.map((q,j)=>subtree(builderDrag.i,j)?[q[0]+dx,q[1]+dy]:q.slice());paintBuilder()};$('builderCanvas').onpointerup=$('builderCanvas').onpointercancel=()=>builderDrag=null;
$('edit').onclick=openBuilder;$('builderClose').onclick=$('applyBuilder').onclick=()=>closeBuilder(true);$('cancelBuilder').onclick=()=>closeBuilder(false);$('lineTool').onclick=()=>{if(draft){draft.types[segment]='line';paintBuilder()}};$('circleTool').onclick=()=>{if(draft){draft.types[segment]='circle';paintBuilder()}};$('fillTool').onclick=()=>{if(draft){draft.types[segment]='circle';draft.filled[segment]=!draft.filled[segment];paintBuilder()}};for(const[id,n]of [['thicker',1.3],['thinner',-1.3]])$(id).onclick=()=>{if(draft){draft.widths[segment]=Math.max(1,Math.min(40,draft.widths[segment]+n));paintBuilder()}};$('dynamicTool').onclick=()=>{if(draft){draft.fixed[segment]=!draft.fixed[segment];paintBuilder()}};$('removeSegment').onclick=()=>{if(draft){draft.hidden=draft.hidden.map((v,j)=>v||subtree(segment,j));paintBuilder()}};$('restoreSegments').onclick=()=>{if(draft){draft.hidden.fill(false);paintBuilder()}};$('resetBuilder').onclick=()=>{if(draft){const f=figure(...draft.points[0]);f.id=draftId;draft=f;paintBuilder()}};
let windowDrag=null;$('builderTitle').onpointerdown=e=>{if(e.target.closest('button')||$('builder').classList.contains('maximized'))return;const b=$('builder');windowDrag={x:e.clientX,y:e.clientY,left:b.offsetLeft,top:b.offsetTop};b.style.right='auto';$('builderTitle').setPointerCapture(e.pointerId)};$('builderTitle').onpointermove=e=>{if(!windowDrag)return;const b=$('builder'),parent=b.parentElement;b.style.left=Math.max(0,Math.min(parent.clientWidth-b.offsetWidth,windowDrag.left+e.clientX-windowDrag.x))+'px';b.style.top=Math.max(0,Math.min(parent.clientHeight-23,windowDrag.top+e.clientY-windowDrag.y))+'px'};$('builderTitle').onpointerup=$('builderTitle').onpointercancel=()=>windowDrag=null;
$('builderMin').onclick=()=>{$('builder').classList.toggle('minimized');paintBuilder()};$('builderMax').onclick=()=>{$('builder').classList.remove('minimized');$('builder').classList.toggle('maximized');paintBuilder()};$('appMin').onclick=()=>$('application').classList.toggle('minimized');$('appMax').onclick=()=>{$('application').classList.remove('minimized');$('application').classList.toggle('restored')};const exit=()=>location.href=location.pathname.includes('/animator/')?'../index.html':'https://github.com/YesterdaysLemon/frame-by-frame';$('appClose').onclick=$('exit').onclick=exit;
function closeMenus(){document.querySelectorAll('.menu').forEach(m=>{m.querySelector('button').setAttribute('aria-expanded','false');m.querySelector('.dropdown').hidden=true})}document.querySelectorAll('.menu').forEach(m=>{const b=m.querySelector('button'),d=m.querySelector('.dropdown');b.onclick=e=>{e.stopPropagation();const show=d.hidden;closeMenus();d.hidden=!show;b.setAttribute('aria-expanded',String(show))};d.onclick=e=>{if(e.target.closest('button'))closeMenus()}});document.addEventListener('click',e=>{if(!e.target.closest('.menu'))closeMenus()});$('help').onclick=$('builderHelp').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();
document.onkeydown=e=>{if($('helpDialog').open)return;if(e.key==='Escape'){closeMenus();closeBuilder(false);return}if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if((e.ctrlKey||e.metaKey)&&['s','o','n','z'].includes(e.key.toLowerCase())){e.preventDefault();$({s:'save',o:'load',n:'new',z:'undo'}[e.key.toLowerCase()]).click();return}if(e.code==='Space'){e.preventDefault();toggle()}if(e.key==='ArrowRight'){e.preventDefault();if(current===frames.length-1)addFrame();else{closeBuilder(true);stop();current++;selected=frame().figures[0]?.id;update(false)}}if(e.key==='ArrowLeft'){e.preventDefault();closeBuilder(true);stop();current=Math.max(0,current-1);selected=frame().figures[0]?.id;update(false)}};
sample();let restored=false;try{const d=JSON.parse(localStorage.getItem('frame-by-frame-v1'));if(valid(d)){adopt(d);restored=true;say('Restored your saved animation.')}}catch{}update(false);speedLabel();new ResizeObserver(()=>{paint();paintBuilder()}).observe($('stagewrap')||cv.parentElement);new ResizeObserver(paintBuilder).observe($('builderCanvas'));requestAnimationFrame(tick);if(!restored)openBuilder();
