'use strict';
// Local reusable assets. Names are rendered as text, and files are validated before use.
const LIBRARY_KEY='frame-by-frame-library-v1', MAX_LIBRARY_BYTES=4_000_000, MAX_ASSETS=120;
let assetLibrary={characters:[],rigs:[],animations:[]},libraryTab='characters',assetSelection=null,previewFrame=0,previewPlaying=false,previewTick=0,previewRequest=0,libraryBlocked=false,rawLibrary='';
const cleanFigure=f=>{const out={id:f.id,color:f.color,points:clone(f.points)};for(const key of ['templatePoints','scale','widths','types','fixed','hidden','filled'])if(f[key]!==undefined)out[key]=clone(f[key]);return normalize(out)};
const freshAssetId=()=>globalThis.crypto?.randomUUID?.()||('asset-'+Date.now()+'-'+Math.random().toString(36).slice(2));
const assetCount=lib=>Object.values(lib).reduce((n,list)=>n+list.length,0);
const assetProject=asset=>asset.project||{version:1,fps:asset.fps,frames:asset.frames};
function validAsset(asset,kind){return asset&&typeof asset.name==='string'&&asset.name.trim().length>0&&asset.name.length<=60&&(kind==='animations'?valid(assetProject(asset)):valid({version:1,fps:12,frames:[{figures:[asset.figure]}]}))}
function validLibrary(data){return data&&data.format==='frame-by-frame-library'&&data.version===1&&['characters','rigs','animations'].every(k=>Array.isArray(data[k])&&data[k].length<=MAX_ASSETS&&data[k].every(a=>validAsset(a,k)))&&assetCount({characters:data.characters,rigs:data.rigs,animations:data.animations})<=MAX_ASSETS}
function cleanAsset(asset,kind){const out={id:freshAssetId(),name:asset.name.trim()};if(kind==='animations'){const p=assetProject(asset);out.project={version:1,fps:p.fps,frames:p.frames.map(fr=>({figures:fr.figures.map(cleanFigure)}))}}else out.figure=cleanFigure(asset.figure);return out}
function librarySay(message){$('libraryStatus').textContent=message}
function persistLibrary(next){if(libraryBlocked){librarySay('Stored library is unreadable. Export its backup before using Reset saved library.');return false}const payload=JSON.stringify({format:'frame-by-frame-library',version:1,...next});if(assetCount(next)>MAX_ASSETS||new Blob([payload]).size>MAX_LIBRARY_BYTES){librarySay('Library limit reached (120 assets / 4 MB). Export a backup and delete unused items.');return false}try{localStorage.setItem(LIBRARY_KEY,payload);assetLibrary=next;rawLibrary=payload;refreshFigurePicker();return true}catch{librarySay('Could not save: browser storage is full or unavailable. Export your work before closing.');return false}}
try{rawLibrary=localStorage.getItem(LIBRARY_KEY)||'';if(rawLibrary){const data=JSON.parse(rawLibrary);if(!validLibrary(data))throw Error('Invalid library');for(const kind of ['characters','rigs','animations'])assetLibrary[kind]=data[kind].map(a=>({...cleanAsset(a,kind),id:typeof a.id==='string'?a.id:freshAssetId()}))}}catch{libraryBlocked=true}

function builtFigure(name,color,limbScale=1){const f=figure(400,350);f.id=1;f.color=color;f.points=builderBase.map(p=>[400+p[0]*limbScale,350+p[1]*limbScale]);f.templatePoints=clone(f.points);return{id:'builtin-'+name.toLowerCase().replace(/\W+/g,'-'),name,builtin:true,figure:f}}
const builtinCharacters=[builtFigure('Classic Stickman','#000000'),builtFigure('Blue Ink','#164ca0'),builtFigure('Roundbot','#474747',.9)];
builtinCharacters[2].figure.types[1]='circle';builtinCharacters[2].figure.widths[1]=12;builtinCharacters[2].figure.widths[2]=12;
const builtinRigs=[builtFigure('Standard rig','#000000'),builtFigure('Long-limbed rig','#000000',1.25),builtFigure('Compact rig','#000000',.7)];
const builtinClips=(window.AnimationPresets||[]).map(p=>({...p,id:'builtin-'+p.id,builtin:true}));
const builtinAssets={characters:builtinCharacters,rigs:builtinRigs,animations:builtinClips};
function tabAssets(){return[...builtinAssets[libraryTab],...assetLibrary[libraryTab]]}
function selectedAsset(){return tabAssets().find(a=>a.id===assetSelection)}
function singleActor(project){const first=project.frames[0].figures[0]?.id;return first!==undefined&&project.frames.every(fr=>fr.figures.length===1&&fr.figures[0].id===first)}
const previewBoundsCache=new WeakMap();
function figureBounds(figures){let left=Infinity,right=-Infinity,top=Infinity,bottom=-Infinity;for(const f of figures)for(const [x,y]of f.points){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y)}return Number.isFinite(left)?{left:left-24,right:right+24,top:top-24,bottom:bottom+24}:null}
function clipBounds(asset){if(!previewBoundsCache.has(asset))previewBoundsCache.set(asset,figureBounds(assetProject(asset).frames.flatMap(fr=>fr.figures)));return previewBoundsCache.get(asset)}
function fitPreview(canvas,figures,bounds=figureBounds(figures)){const {c,w,h}=sizeCanvas(canvas);c.fillStyle='#fff';c.fillRect(0,0,w,h);if(!bounds)return;const {left:x0,right:x1,top:y0,bottom:y1}=bounds,s=Math.min(w/Math.max(1,x1-x0),h/Math.max(1,y1-y0));c.save();c.translate((w-(x1-x0)*s)/2-x0*s,(h-(y1-y0)*s)/2-y0*s);c.scale(s,s);figures.forEach(f=>drawFigure(c,f));c.restore()}
function drawAssetPreview(){const a=selectedAsset();if(!a){fitPreview($('libraryPreview'),[]);$('previewInfo').textContent='Select an item';return}if(libraryTab==='animations'){const p=assetProject(a);previewFrame%=p.frames.length;fitPreview($('libraryPreview'),p.frames[previewFrame].figures,clipBounds(a));$('previewInfo').textContent=`${previewFrame+1} / ${p.frames.length} frames · ${p.fps} fps`}else{fitPreview($('libraryPreview'),[a.figure]);$('previewInfo').textContent=libraryTab==='rigs'?'11 joints · reusable geometry':'Character · pose and appearance'}}
function stopPreview(){previewPlaying=false;cancelAnimationFrame(previewRequest);$('previewPlay').textContent='▶ Preview'}
function animatePreview(t){if(!previewPlaying||$('libraryWindow').hidden)return;const a=selectedAsset();if(!a)return;const p=assetProject(a);const interval=1000/p.fps,steps=Math.floor((t-previewTick)/interval);if(steps>0){previewFrame=(previewFrame+steps)%p.frames.length;previewTick+=steps*interval;drawAssetPreview()}previewRequest=requestAnimationFrame(animatePreview)}
function updateAssetControls(){const a=selectedAsset(),anim=libraryTab==='animations';$('insertAsset').textContent=anim?'Append clip':'Add to frame';$('insertAsset').disabled=!a;$('openAnimation').hidden=!anim;$('openAnimation').disabled=!a;$('previewPlay').hidden=!anim;$('previewPlay').disabled=!a;$('renameAsset').disabled=!a||!!a.builtin;$('deleteAsset').disabled=!a||!!a.builtin;$('saveAsset').textContent=anim?'Save current animation':libraryTab==='rigs'?'Save current rig':'Save current character';$('useSelectedFigure').parentElement.hidden=!anim;$('useSelectedFigure').disabled=!a||!chosen()||(anim&&!singleActor(assetProject(a)));$('assetDescription').textContent=a?(a.description||(a.builtin?'Built-in example. ': 'Saved in this browser. ')+(anim?'Open it or append its frames to your animation.':libraryTab==='rigs'?'Template geometry, thickness and joint constraints.':'Current pose, colour and segment styling.')):'Select an item to preview, or save your current work below.';drawAssetPreview()}
function renderLibrary(){const q=$('librarySearch').value.trim().toLowerCase(),items=tabAssets().filter(a=>a.name.toLowerCase().includes(q)),list=$('libraryList');list.replaceChildren();if(!items.some(a=>a.id===assetSelection))assetSelection=items[0]?.id||null;for(const a of items){const b=document.createElement('button');b.className='library-item';b.setAttribute('role','option');b.setAttribute('aria-selected',String(a.id===assetSelection));b.setAttribute('aria-label',a.name);const canvas=document.createElement('canvas');canvas.width=90;canvas.height=70;const label=document.createElement('span');label.className='item-name';label.textContent=a.name;const type=document.createElement('span');type.className='item-kind';type.textContent=a.builtin?'Built-in':libraryTab==='animations'?'Saved animation':libraryTab==='rigs'?'Saved rig':'Saved character';label.append(type);b.append(canvas,label);b.onclick=()=>{stopPreview();assetSelection=a.id;previewFrame=0;$('assetName').value=a.name;renderLibrary()};b.ondblclick=()=>{if(libraryTab!=='animations')insertAsset()};list.append(b);fitPreview(canvas,libraryTab==='animations'?assetProject(a).frames[0].figures:[a.figure])}if(!items.length){const empty=document.createElement('div');empty.className='library-empty';empty.textContent=q?'No matching items.':'Nothing saved yet.';list.append(empty)}$('libraryCount').textContent=`${items.length} items · ${assetLibrary[libraryTab].length} saved`;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===libraryTab)));updateAssetControls()}
function openLibrary(tab='characters',saveMode=false){libraryTab=tab;stopPreview();$('libraryWindow').hidden=false;$('libraryWindow').classList.remove('minimized');$('librarySearch').value='';assetSelection=null;previewFrame=0;renderLibrary();$('assetName').value=saveMode?'New '+(tab==='animations'?'animation':tab==='rigs'?'rig':'character'):(selectedAsset()?.name||'New item');librarySay(libraryBlocked?'Stored library could not be read. Export a backup before resetting it.':'Saved in this browser. Export a library file for a portable backup.');if(saveMode){$('assetName').focus();$('assetName').select()}}
function closeLibrary(){$('libraryWindow').hidden=true;stopPreview()}
function uniqueName(name,kind){const baseName=name.trim().slice(0,60)||'Untitled';let result=baseName,n=2;while([...builtinAssets[kind],...assetLibrary[kind]].some(a=>a.name.toLowerCase()===result.toLowerCase())){const suffix=' ('+n+++')';result=baseName.slice(0,60-suffix.length)+suffix}return result}
function saveAsset(){const kind=libraryTab,name=uniqueName($('assetName').value,kind);let record={id:freshAssetId(),name};if(kind==='animations'){closeBuilder(true);record.project={version:1,fps:+$('fps').value,frames:frames.map(fr=>({figures:fr.figures.map(cleanFigure)}))}}else{const source=kind==='rigs'?(draft||chosen()):chosen();if(!source)return librarySay('Select a figure on the stage first.');record.figure=cleanFigure(source);record.figure.id=1;if(kind==='rigs'){record.figure.points=clone(draft?source.points:source.templatePoints||source.points);record.figure.templatePoints=clone(record.figure.points);record.figure.color='#000000'}}if(!validAsset(record,kind))return librarySay('This item could not be saved because its geometry is invalid.');const next=clone(assetLibrary);next[kind].push(record);if(persistLibrary(next)){assetSelection=record.id;$('assetName').value=name;$('librarySearch').value='';renderLibrary();librarySay('Saved “'+name+'”. It will be available after reopening the browser.')}}
function refreshFigurePicker(){const picker=$('figureType'),old=picker.value;picker.replaceChildren();const baseOption=document.createElement('option');baseOption.value='stickman';baseOption.textContent='Stickman';picker.append(baseOption);for(const kind of ['characters','rigs']){if(!assetLibrary[kind].length)continue;const group=document.createElement('optgroup');group.label=kind==='rigs'?'Saved rigs':'Saved characters';assetLibrary[kind].forEach(a=>{const o=document.createElement('option');o.value=kind+':'+a.id;o.textContent=a.name;group.append(o)});picker.append(group)}if([...picker.options].some(o=>o.value===old))picker.value=old}
function insertFigureAsset(asset){if(frame().figures.length>=50)return librarySay('The current frame already has 50 figures.');mutate(()=>{const f=cleanFigure(asset.figure),origin=f.points[0].slice(),dx=400-origin[0],dy=350-origin[1];f.id=++serial;f.points=f.points.map(p=>[p[0]+dx,p[1]+dy]);if(f.templatePoints){const o=f.templatePoints[0];f.templatePoints=f.templatePoints.map(p=>[p[0]+400-o[0],p[1]+350-o[1]])}frame().figures.push(f);selected=f.id});librarySay('Added “'+asset.name+'” to frame '+(current+1)+'.')}
function retarget(source,target,firstSource){const f=cleanFigure(target),lengths=f.templatePoints||f.points,origin=target.points[0],a=firstSource.points[0],p=source.points[0],sourceHeight=Math.hypot(...[firstSource.points[0][0]-firstSource.points[2][0],firstSource.points[0][1]-firstSource.points[2][1]]),targetHeight=Math.hypot(lengths[0][0]-lengths[2][0],lengths[0][1]-lengths[2][1]),ratio=targetHeight/Math.max(1,sourceHeight);f.points=[[origin[0]+(p[0]-a[0])*ratio,origin[1]+(p[1]-a[1])*ratio]];for(let i=1;i<11;i++){const parent=parents[i],srcParent=source.points[parent],src=source.points[i],length=Math.hypot(lengths[i][0]-lengths[parent][0],lengths[i][1]-lengths[parent][1]),angle=f.fixed[i]?Math.atan2(lengths[i][1]-lengths[parent][1],lengths[i][0]-lengths[parent][0]):Math.atan2(src[1]-srcParent[1],src[0]-srcParent[0]);f.points[i]=[f.points[parent][0]+Math.cos(angle)*length,f.points[parent][1]+Math.sin(angle)*length]}return f}
function insertAsset(){const a=selectedAsset();if(!a)return;if(libraryTab!=='animations'){insertFigureAsset(a);return}const p=assetProject(a);if(frames.length+p.frames.length>500)return librarySay('Not enough room: this clip would exceed 500 frames.');const target=chosen(),useTarget=$('useSelectedFigure').checked&&target&&singleActor(p),baseline=clone(frame()),map=new Map();const additions=p.frames.map(fr=>{if(useTarget){const posed=retarget(fr.figures[0],target,p.frames[0].figures[0]);return{figures:baseline.figures.map(f=>f.id===target.id?posed:clone(f))}}return{figures:fr.figures.map(f=>{const n=cleanFigure(f);if(!map.has(f.id))map.set(f.id,++serial);n.id=map.get(f.id);return n})}});mutate(()=>{frames.splice(current+1,0,...additions);current++;selected=frame().figures[0]?.id;if(useTarget)selected=target.id});librarySay(`Appended ${additions.length} frames${useTarget?' using the selected character’s rig and appearance':''} at ${$('fps').value} fps. Undo removes the clip.`)}
function openAnimation(){const a=selectedAsset();if(!a||libraryTab!=='animations')return;if(!confirm('Open “'+a.name+'”? This replaces the current animation. Undo will restore it.'))return;const p=assetProject(a);mutate(()=>{frames=p.frames.map(fr=>({figures:fr.figures.map(cleanFigure)}));serial=Math.max(serial,...frames.flatMap(fr=>fr.figures.map(f=>f.id)));current=0;selected=frame().figures[0]?.id;$('fps').value=p.fps});speedLabel();librarySay('Opened “'+a.name+'”. Undo restores the previous animation.');closeLibrary()}
$('openCharacters').onclick=()=>openLibrary('characters');$('openAnimations').onclick=()=>openLibrary('animations');$('saveCharacterMenu').onclick=()=>openLibrary('characters',true);$('saveRigMenu').onclick=$('saveBuilderRig').onclick=()=>openLibrary('rigs',true);$('saveAnimationMenu').onclick=()=>openLibrary('animations',true);$('saveAsset').onclick=saveAsset;$('insertAsset').onclick=insertAsset;$('openAnimation').onclick=openAnimation;$('libraryClose').onclick=closeLibrary;
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>openLibrary(b.dataset.tab));$('librarySearch').oninput=()=>{stopPreview();renderLibrary()};$('previewPlay').onclick=()=>{if(previewPlaying){stopPreview();return}if(libraryTab!=='animations'||!selectedAsset())return;previewPlaying=true;previewTick=performance.now();$('previewPlay').textContent='■ Stop';previewRequest=requestAnimationFrame(animatePreview)};
$('renameAsset').onclick=()=>{const a=selectedAsset();if(!a||a.builtin)return;const name=$('assetName').value.trim();if(!name)return librarySay('Enter a name first.');if(tabAssets().some(other=>other.id!==a.id&&other.name.toLowerCase()===name.toLowerCase()))return librarySay('An item already has that name.');const next=clone(assetLibrary);next[libraryTab].find(r=>r.id===a.id).name=name.slice(0,60);if(persistLibrary(next)){renderLibrary();librarySay('Item renamed.')}};
$('deleteAsset').onclick=()=>{const a=selectedAsset();if(!a||a.builtin)return;if(!confirm('Delete “'+a.name+'” from this browser’s library? Existing animation frames are kept.'))return;const next=clone(assetLibrary);next[libraryTab]=next[libraryTab].filter(r=>r.id!==a.id);if(persistLibrary(next)){stopPreview();assetSelection=null;renderLibrary();librarySay('Library item deleted. Existing frames were kept.')}};
$('libraryExport').onclick=()=>{download(new Blob([libraryBlocked?rawLibrary:JSON.stringify({format:'frame-by-frame-library',version:1,...assetLibrary},null,2)],{type:'application/json'}),libraryBlocked?'library-recovery.json':'frame-by-frame-library.json');librarySay('Library backup downloaded.')};$('libraryImport').onclick=()=>$('libraryFile').click();$('libraryFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>MAX_LIBRARY_BYTES)throw Error('size');const data=JSON.parse(await file.text());if(!validLibrary(data))throw Error('format');const next=clone(assetLibrary);for(const kind of ['characters','rigs','animations'])for(const a of data[kind]){const item=cleanAsset(a,kind);let name=item.name,n=2;while([...builtinAssets[kind],...next[kind]].some(v=>v.name.toLowerCase()===name.toLowerCase())){const suffix=' ('+n+++')';name=item.name.slice(0,60-suffix.length)+suffix}item.name=name;next[kind].push(item)}if(persistLibrary(next)){renderLibrary();librarySay('Library imported. Existing items were preserved; duplicate names were numbered.')}}catch{librarySay('Could not import: choose a valid Frame by Frame library JSON file under 4 MB.')}e.target.value=''};
$('libraryReset').onclick=()=>{if(!confirm('Remove all saved library items from this browser? Export a backup first. Built-in assets and your current animation are kept.'))return;try{localStorage.removeItem(LIBRARY_KEY);libraryBlocked=false;assetLibrary={characters:[],rigs:[],animations:[]};rawLibrary='';refreshFigurePicker();renderLibrary();librarySay('Saved library cleared. Your animation and built-in assets are unchanged.')}catch{librarySay('Browser storage is unavailable.')}};
const originalAddFigure=$('add').onclick;$('add').onclick=()=>{const value=$('figureType').value;if(value==='stickman'){originalAddFigure();return}const split=value.indexOf(':'),kind=value.slice(0,split),id=value.slice(split+1),a=assetLibrary[kind]?.find(r=>r.id===id);if(a)insertFigureAsset(a)};
let libraryWindowDrag=null;$('libraryTitle').onpointerdown=e=>{if(e.target.closest('button')||$('libraryWindow').classList.contains('maximized'))return;const b=$('libraryWindow');libraryWindowDrag={x:e.clientX,y:e.clientY,left:b.offsetLeft,top:b.offsetTop};$('libraryTitle').setPointerCapture(e.pointerId)};$('libraryTitle').onpointermove=e=>{if(!libraryWindowDrag)return;const b=$('libraryWindow');b.style.left=Math.max(0,Math.min(innerWidth-b.offsetWidth,libraryWindowDrag.left+e.clientX-libraryWindowDrag.x))+'px';b.style.top=Math.max(0,Math.min(Math.max(0,innerHeight-b.offsetHeight),libraryWindowDrag.top+e.clientY-libraryWindowDrag.y))+'px'};$('libraryTitle').onpointerup=$('libraryTitle').onpointercancel=()=>libraryWindowDrag=null;
$('libraryMin').onclick=()=>{$('libraryWindow').classList.toggle('minimized');stopPreview()};$('libraryMax').onclick=()=>{$('libraryWindow').classList.remove('minimized');$('libraryWindow').classList.toggle('maximized');drawAssetPreview()};window.addEventListener('resize',()=>{for(const id of ['builder','libraryWindow']){const win=$(id);if(win.hidden||win.classList.contains('maximized'))continue;const r=win.getBoundingClientRect();if(r.right>innerWidth){win.style.left=Math.max(0,innerWidth-r.width-4)+'px';win.style.right='auto'}if(r.bottom>innerHeight)win.style.top=Math.max(0,innerHeight-r.height-4)+'px'}});new ResizeObserver(drawAssetPreview).observe($('libraryPreview'));refreshFigurePicker();
